[package]
name = "glium_text"
version = "0.5.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Text drawing with glium and freetype"
keywords = ["text", "opengl"]
license = "MIT"

[dependencies]
freetype-sys = "0.1"
libc = "0.1"

[dependencies.glium]
version = "0.9"
default-features = false
features = ["cgmath"]

[dev-dependencies]
cgmath = "0.2"

[dev-dependencies.glium]
version = "0.9"
features = ["glutin"]
